apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-steps-template-
spec:
  entrypoint: steps-template-serial
  templates:
    - name: steps-template-serial
      steps:
        - - name: step1
            template: task-template
        - - name: step2
            template: task-template
          - name: step3
            template: task-template
        - - name: step4
            template: task-template
    - name: task-template
      script:
        image: python:3.8-slim
        command: [python]
        source: |
          print("My name is Zuzu")
          age = 18
          print("My age is {}".format(age))