apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-resource-template-
spec:
  entrypoint: resource-template
  templates:
    - name: resource-template
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: wf-resource-created-
          spec:
            entrypoint: test-template
            templates:
              - name: test-template
                script:
                  image: python:3.8-slim
                  command: [python]
                  source: |
                    print("Hello! My name is Zeyad and I am learning argo")
                    print("This has been created using the resouce template")