apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-dag-template-
spec:
  entrypoint: dag-template
  arguments:
    parameters:
    - name: message1
      value: "12"
    - name: message2
      value: "15"
    - name: message3
      value: "19"
    - name: message4
      value: "21"
  templates:
    - name: dag-template
      inputs:
        parameters:
        - name: message1
        - name: message2
        - name: message3
        - name: message4
      dag:
        tasks:
          - name: task1
            arguments:
              parameters: [{name: age, value: "{{inputs.parameters.message1}}"}]
            template: task-template
          - name: task2
            arguments:
              parameters: [{name: age, value: "{{inputs.parameters.message2}}"}]
            template: task-template
            dependencies: [task1]
          - name: task3
            arguments:
              parameters: [{name: age, value: "{{inputs.parameters.message3}}"}]
            template: task-template
            dependencies: [task1]
          - name: task4
            arguments:
              parameters: [{name: age, value: "{{inputs.parameters.message4}}"}]
            template: task-template
            dependencies: [task2, task3]

    - name: task-template
      inputs:
        parameters:
        - name: age
      script:
        image: python:3.8-slim
        command: [python]
        source: |
          age = "{{inputs.parameters.age}}"
          print("My name is Zuzu")
          print("My age is {}".format(age))